Fix: add bedrock branch logic while creating kg index (#574)
Error occurred when using bedrock as llm provider caused by malformed
input request.

botocore.errorfactory.ValidationException: An error occurred
(ValidationException) when calling the InvokeModel operation: Malformed
input request: #: subject must not be valid against schema
{"required":["messages"]}#: extraneous key [response_mime_type] is not
permitted, please reformat your input and try again.